### ISSUE TITLE
Nelze zkompilovat

### ISSUE THREAD

**Issue by HynekBaran** [PepaRokos/pvr.sledovanitv#1]
Dobrý den,
pokusil jsem se zkompilovat Vaši knihovnu, avšak čvrtý krok

cmake -DADDONS_TO_BUILD=pvr.sledovanitv -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons

selhal s chybovým hlášením
CMake Error: The source directory "/opt/sledovanitv/xbmc/project/cmake/addons" does not appear to contain CMakeLists.txt.

V příslušném adresáři  skutečně CMakeLists.txt není.

Můžete mi prosím poradit? Děkuji 
[sledovanitv.tree.zip](https://github.com/PepaRokos/pvr.sledovanitv/files/681387/sledovanitv.tree.zip)

**Comment by PepaRokos** [comment]
Dobrý den,

v současnosti lze plugin zkompilovat pouze pro Kodi verze Isengard a Jarvis. Oba repozitáře (jak tento, tak xbmc) musí být přepnuté do větve verze pro kterou chcete kompilovat (git checkout Jarvis). Na novější verze se snad taky časem dostane.

**Comment by HynekBaran** [comment]
Děkuji za odpověď, to mne nenapadlo. Mám v. 16.1 a po provedení git checkout Jarvis v obou repozitářích skončí pokus o cmake jinou chybou:
`# cmake -DADDONS_TO_BUILD=pvr.sledovanitv -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /opt/sledovanitv/pvr.sledovanitv/build/build/zips)
-- Building following addons: pvr.sledovanitv
-- Overriding addon source directory prefix: /opt/sledovanitv/xbmc/project
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;platform
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/platform/platform.txt
-- platform url: https://github.com/Pulse-Eight/platform.git
-- No platform specific file /opt/sledovanitv/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
CMake Error at CMakeLists.txt:394 (message):
  pvr.sledovanitv: invalid or missing addon source directory at
  /opt/sledovanitv/xbmc/project/pvr.sledovanitv


-- Configuring incomplete, errors occurred!`


[CMakeOutput.log.zip](https://github.com/PepaRokos/pvr.sledovanitv/files/682975/CMakeOutput.log.zip)

**Comment by PepaRokos** [comment]
Vypadá to, že nestojíte v adresáři /opt/sledovanitv/pvr.sledovanitv/build. Podle toho co to vypsalo, to vypadá, že je cmake spouštěn z /opt/sledovanitv/xbmc/project/. Umístění zdrojáků udává proměnná ADDON_SRC_PREFIX. Musí existovat ADDON_SRC_PREFIX/pvr.sledovánítv a musí obsahovat zdrojáky addonu.

**Comment by HynekBaran** [comment]
Nikoli. Spuštěno z /opt/sledovanitv/pvr.sledovanitv/build

**Comment by HynekBaran** [comment]
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls ../..
pvr.sledovanitv  xbmc

**Comment by HynekBaran** [comment]
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls ../../pvr.sledovanitv/
build  CMakeLists.txt  depends	FindJsonCpp.cmake  pvr.sledovanitv  README.md  src  xbmc

**Comment by HynekBaran** [comment]
Nešlo by prosím přidat ke stažení zkompilovaný projekt?

**Comment by HynekBaran** [comment]
Snad je vodítkem zpráva
-- No platform specific file /opt/sledovanitv/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
přitom
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls /opt/sledovanitv/xbmc/project/cmake/addons/depends/
CMakeLists.txt	common	README	windows

**Comment by HynekBaran** [comment]
Dobrý den,
po čase a čisté reinstalaci OSMC jsem se vrátil k pokusu o kompilaci Vašeho doplňku, který by se zejména mým dětem velice líbil. Postupoval jsem dle pokynů vč. `git checkout Jarvis` v obou repozitářích a dopadl jsem stejně jako minule:
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# cmake -DADDONS_TO_BUILD=pvr.sledovanitv -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /opt/sledovanitv/pvr.sledovanitv/build/build/zips)
-- Building following addons: pvr.sledovanitv
-- Overriding addon source directory prefix: /opt/sledovanitv/xbmc/project
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/platform/platform.txt
-- platform url: https://github.com/Pulse-Eight/platform.git
-- Found Git: /usr/bin/git (found version "2.1.4") 
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;platform
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /opt/sledovanitv/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
CMake Error at CMakeLists.txt:394 (message):
  pvr.sledovanitv: invalid or missing addon source directory at
  /opt/sledovanitv/xbmc/project/pvr.sledovanitv


-- Configuring incomplete, errors occurred!
See also "/opt/sledovanitv/pvr.sledovanitv/build/CMakeFiles/CMakeOutput.log".
```
Ověřil jsem, co je  v 

> /opt/sledovanitv/xbmc/project/cmake/addons/depends/

```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls /opt/sledovanitv/xbmc/project/cmake/addons/depends/
CMakeLists.txt	common	README	windows
```
a jelikož jsem mé OSMC běží na linuxu na Raspberry Pi, není divu, že to nefunguje.
Nedokážete prosím poradit, co s tím?
[CMakeOutput.log.zip](https://github.com/PepaRokos/pvr.sledovanitv/files/811843/CMakeOutput.log.zip)

**Comment by PepaRokos** [comment]
Dobrý den,
chybová hláška mluví celkem jasně:
`CMake Error at CMakeLists.txt:394 (message):
  pvr.sledovanitv: invalid or missing addon source directory at
  /opt/sledovanitv/xbmc/project/pvr.sledovanitv`
Vypadá to, že cesta zadaná v ADDON_SRC_PREFIX se vyhodnotí rtelativně k /opt/sledovanitv/xbmc/project/cmake/addons ač by měla k /opt/sledovanitv/pvr.sledovanitv/build. Pomohlo by tedy nejspíš zxadat cestu jako ../../../.., případně zadat absolutní cestu /opt/sledovanitv (parametr -DADDON_SRC_PREFIX).

**Comment by HynekBaran** [comment]
Díky, je na to jsem nepřišel. Nyní proběhne make bez explicitní chyby, ale stejně se nevygeneroval zip s výsledkem:
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# cmake -DADDONS_TO_BUILD=../../../.. -DADDON_SRC_PREFIX=../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /opt/sledovanitv/pvr.sledovanitv/build/build/zips)
-- Building following addons: ../../../..
-- Overriding addon source directory prefix: /opt/sledovanitv/xbmc/project
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/platform/platform.txt
-- platform url: https://github.com/Pulse-Eight/platform.git
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;platform
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /opt/sledovanitv/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/sledovanitv/pvr.sledovanitv/build
```
Pro kontrolu:
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls /opt/sledovanitv/pvr.sledovanitv/build
build  CMakeCache.txt  CMakeFiles  cmake_install.cmake	depends  Makefile
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls /opt/sledovanitv/pvr.sledovanitv/build/build/
depends  download  kodi-platform  platform  tinyxml
```
ale /opt/sledovanitv/pvr.sledovanitv/build/build/zips tam není :( 
Pořád je mi ale divné, že
```
root@osmc:/opt/sledovanitv# ls /opt/sledovanitv/xbmc/project/cmake/addons/depends/
CMakeLists.txt	common	README	windows
```

Nebo zas jen něčemu nerozumím?

**Comment by HynekBaran** [comment]
Ještě jsem si uvědomil, že jste to možná myslel takto:
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# cmake -DADDONS_TO_BUILD=pvr.sledovanitv -DADDON_SRC_PREFIX=../../../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons
-- Addon source tarball caching is enabled
-- ZIP packaging enabled (destination: /opt/sledovanitv/pvr.sledovanitv/build/build/zips)
-- Building following addons: pvr.sledovanitv
-- Overriding addon source directory prefix: /opt/sledovanitv
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/platform/platform.txt
-- platform url: https://github.com/Pulse-Eight/platform.git
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/kodi-platform/kodi-platform.txt
-- kodi-platform url: https://github.com/xbmc/kodi-platform
-- kodi-platform depends: tinyxml;platform
-- Processing /opt/sledovanitv/xbmc/project/cmake/addons/depends/common/tinyxml/tinyxml.txt
-- tinyxml url: http://mirrors.kodi.tv/build-deps/sources/tinyxml-2.6.2_2.tar.gz
-- No platform specific file /opt/sledovanitv/xbmc/project/cmake/addons/depends/linux/CMakeLists.txt found
-- Processing /opt/sledovanitv/pvr.sledovanitv/depends/common/jsoncpp/jsoncpp.txt
-- jsoncpp url: http://mirrors.kodi.tv/build-deps/sources/jsoncpp-src-0.5.0.tar.gz
-- pvr.sledovanitv DEPENDENCIES: jsoncpp
-- Configuring done
-- Generating done
-- Build files have been written to: /opt/sledovanitv/pvr.sledovanitv/build
```
Ale výsledek není o mnoho lepší:
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls /opt/sledovanitv/pvr.sledovanitv/build
CMakeCache.txt	CMakeFiles  cmake_install.cmake  depends  Makefile  pvr.sledovanitv-prefix
```

**Comment by PepaRokos** [comment]
Cmake je první fáze- zkonfiguruje projekt podle cílové platformy, umístění knihoven, atd vygeneruje makefile, případně projektový soubor pro IDE (viz cmake.org). Pak je potřeba spustit vlastní build příkazem make (bod 5 v README). Výsledek se vygeneruje do cesty zadané parametrem CMAKE_INSTALL_PREFIX. Zabilit se to musí ručně, zip mi to negeneruje i když soudě podle parametru PACKAGE_ZIP by mohlo. Ještě je možné, že make skončí s tím, že nemůže najít projekt kodi, to se dá vyřešit nastavením systémové proměnné kodi_DIR=/opt/sledovanitv/xbmc/project/cmake před make:
`root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# kodi_DIR=/opt/sledovanitv/xbmc/project/cmake make`

**Comment by HynekBaran** [comment]
Jsem osel, na make jsem zapoměl. Proběhl bez chyby, ale stejně nevidím výsledek. 
```
root@osmc:/opt/sledovanitv/pvr.sledovanitv/build# ls ../../xbmc/addons
audioencoder.xbmc.builtin.aac  library.xbmc.addon		metadata.common.theaudiodb.com	      screensaver.xbmc.builtin.dim  xbmc.core
audioencoder.xbmc.builtin.wma  library.xbmc.codec		metadata.common.themoviedb.org	      script.module.pil		    xbmc.gui
kodi.adsp		       library.xbmc.pvr			metadata.local			      service.xbmc.versioncheck     xbmc.json
kodi.audiodecoder	       metadata.album.universal		metadata.themoviedb.org		      share			    xbmc.metadata
kodi.guilib		       metadata.artists.universal	metadata.tvdb.com		      skin.confluence		    xbmc.pvr
kodi.resource		       metadata.common.allmusic.com	repository.xbmc.org		      skin.re-touched		    xbmc.python
lib			       metadata.common.fanart.tv	resource.images.weathericons.default  webinterface.default	    xbmc.webinterface
library.kodi.adsp	       metadata.common.htbackdrops.com	resource.language.en_gb		      xbmc.addon
library.kodi.audioengine       metadata.common.imdb.com		resource.uisounds.confluence	      xbmc.audioencoder
library.kodi.guilib	       metadata.common.musicbrainz.org	screensaver.xbmc.builtin.black	      xbmc.codec
```
vše s včerejším datem čili netknuté dnešním make :(((

**Comment by PepaRokos** [comment]
Jestliže vše proběhlo bez chyb, tak by zkompilovaná knihovna měla určitě být ještě v /opt/sledovanitv/pvr.sledovanitv/build/pvr.sledovanitv-prefix/src/pvr.sledovanitv-build. Zip se pak musí sestavit ručně nakopírováním knihovny do /opt/sledovanitv/pvr.sledovanitv/pvr.sledovanitv a zabalením. Soudě podle toho, že byl problém s cestou ke zdrojákům, tak tohle bude asi podobné. 
Jinak ještě doporučuji přepnout build na release, vyjde menší, optimalizovaná binárka (parametr CMAKE_BUILD_TYPE přehodit na Release)

**Comment by HynekBaran** [comment]
Ano, další problém s cestou. Opraveno, dostal jsem
```
ls /opt/sledovanitv/xbmc/addons/.//pvr.sledovanitv
addon.xml  icon.png  pvr.sledovanitv.so  pvr.sledovanitv.so.16.1  pvr.sledovanitv.so.1.9.3  resources
```
Odpoledne vyzkouším, díky moc za rady!

**Comment by HynekBaran** [comment]
Pro pořádek: Funkční cmake byl
`cmake -DADDONS_TO_BUILD=pvr.sledovanitv -DADDON_SRC_PREFIX=../../../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=../../xbmc/addons -DPACKAGE_ZIP=1 ../../xbmc/project/cmake/addons`

**Comment by HynekBaran** [comment]
Tak už to skoro je :)))
Pokus o instalaci doplňku přes GUI ovšem nevyšel:
```
11:41:43.223 T:1958630320   DEBUG: CAddonInstaller: installing from zip '/opt/sledovanitv/xbmc/addons/pvr.sledovanitv.zip'
11:41:43.240 T:1316672496   DEBUG: CAddonInstallJob[pvr.sledovanitv.cz]: requires xbmc.pvr version 4.1.0 which is not available
11:41:43.240 T:1316672496   ERROR: CAddonInstallJob[pvr.sledovanitv.cz]: Závislost na xbmc.pvr verze 4.1.0 nemohla být uspokojena
```

**Comment by johny-mnemonic** [comment]
@HynekBaran Myslím, že tahle chyba znamená, že to instaluješ do jiné verze Kodi, než pro kterou jsi to zkompiloval.

**Comment by PepaRokos** [comment]
Přesně tak. Každý release Kodi má jinou verzi PVR API, takže se doplněk musí kompilovat pro cílovou verzi.

**Comment by HynekBaran** [comment]
Je to tak, omylem jsem kompiloval pro Jarvis, ačkoli mám v. 17. Provedl jsem oba git checkout-y, ale je tu další chyba:
CMake 3.1 or higher is required.  You are running version 3.0.2
apt-get mi ovšem hlásí, že můj cmake je aktuální a já nemám sílu to řešit.

Teprve dnes jsem si všiml, že v záhlaví máte link na svůj web, kde se dá stáhnout binárka, což jsem okamžitě udělal. Je to tam dlouho?
Okamžitě jsem stáhl a zkusil, a zase mám potíže: Přehrávání ze záznamu je ok, ale živé vysílání nejde spustit. U seznamu kanálů jsou všude zámky a když zkusím některý vybrat a přehrát, nic se nestane (ani chyba, ani přehrání, nic).
Pokud poradíte jak, rád dám k dispozici případný log. Napadlo mne jen
```
grep pvr /home/osmc/.kodi/temp/kodi.log
13:50:20.900 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/pvr.sledovanitv.cz_720852387.tbn
13:50:20.903 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály.tbn
13:50:20.904 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.jpg
13:50:20.905 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.jpg
13:50:20.905 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.JPG
13:50:20.906 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.JPG
13:50:20.907 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpg
13:50:20.907 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Cover.jpg
13:50:20.908 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpeg
13:50:20.909 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.jpg
13:50:20.910 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.jpg
13:50:20.910 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.JPG
13:50:20.911 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.JPG
```
a
```
grep "13:50" /home/osmc/.kodi/temp/kodi.log
13:50:20.365 T:1547695088 WARNING: CPVRRecording::CPVRRecording - unable to determine channel type. Defaulting to TV.
13:50:20.900 T:1937765360 WARNING: Previous line repeats 69 times.
13:50:20.900 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/pvr.sledovanitv.cz_720852387.tbn
13:50:20.903 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály.tbn
13:50:20.904 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.jpg
13:50:20.905 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.jpg
13:50:20.905 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.JPG
13:50:20.906 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.JPG
13:50:20.907 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpg
13:50:20.907 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Cover.jpg
13:50:20.908 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpeg
13:50:20.909 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.jpg
13:50:20.910 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.jpg
13:50:20.910 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.JPG
13:50:20.911 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.JPG
13:50:20.916 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/pvr.sledovanitv.cz_909714477.tbn
13:50:20.919 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály.tbn
13:50:20.920 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.jpg
13:50:20.921 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.jpg
13:50:20.922 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/folder.JPG
13:50:20.922 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Folder.JPG
13:50:20.923 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpg
13:50:20.924 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Cover.jpg
13:50:20.924 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/cover.jpeg
13:50:20.925 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.jpg
13:50:20.926 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.jpg
13:50:20.927 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/thumb.JPG
13:50:20.927 T:1937765360 WARNING: CreateLoader - unsupported protocol(pvr) in pvr://channels/radio/Všechny kanály/Thumb.JPG
13:50:21.172 T:1716777968  NOTICE: Start - EPG thread started
13:50:26.829 T:1502602224 WARNING: EPG - UpdateFromScraper - channel not found, can't update
13:50:26.830 T:1502602224   ERROR: EPG - Update - failed to update table 'Radio WOW'
13:50:26.832 T:1502602224 WARNING: EPG - UpdateFromScraper - channel not found, can't update
13:50:26.832 T:1502602224   ERROR: EPG - Update - failed to update table 'Radio Dechovka'
13:50:28.012 T:1502602224  NOTICE: AddOnLog: PVR Sledovanitv.cz: EPG Loaded.
```
Díky moc za všechny rady, až to jednou rozchodím, pozvu vás na pivo ;)

**Comment by PepaRokos** [comment]
Web s binárkami funguje cca měsíc. V poslední verzi jsem změnil dotaz API pro live streamy, zkuste verzi 2.0.1. Jestli to bude fungovat, tak bych to přehodil zpátky. Řešilo to pomalé spouštění streamů kanálů.

**Comment by HynekBaran** [comment]
Je to záhada, dnes jsem to ještě jednou zkusil a funguje to :))) Jupí!
