### ISSUE TITLE
objasnit obcasne neprehravanie nahravok

### ISSUE THREAD

**Issue by jose1711** [PepaRokos/pvr.sledovanitv#12]
> Přehrávání nahrávek- občas nelze pustit nahrávku, protože se zneplatní hash v URL streamu.

toto mi nie je celkom jasne. vsimol som si, ze niekedy, ked dam nieco nahrat, neuvidim to v zozname nahravok v kodi - az do doby, kedy si neotvorim nahravky v browseri na pc. ale to, co popisujete, bude asi iny problem.

na nemoznost spustenia nahravky som zatial nenarazil. pomoze vtedy restart kodi? pripadne odhlasenie a znovuprihlasenie do pvr? dakujem

**Comment by PepaRokos** [comment]
Toto by taky mělo v Kodi 18 fungovat.
