### ISSUE TITLE
EPG len niekolko hodin dopredu

### ISSUE THREAD

**Issue by jose1711** [PepaRokos/pvr.sledovanitv#13]
napriek tomu, ze v kodi (17.6) mam nastavene pre EPG stahovanie na 3 dni dopredu vidim program len na niekolko nasledujucich hodin (a zopar i do minulosti). cez browser mozem listovat az 4 dni do buducnosti.

**Comment by PepaRokos** [comment]
Toto je opravené ve větvi master pro Kodi 18.

**Comment by jose1711** [comment]
backport do vetve Kodi 17 je mozny alebo treba cakat na Kodi 18 release?

**Comment by PepaRokos** [comment]
Nezávisí to na API Kodi, takže backport by šel. Mělo by stačit upravit metodu ApiManager::getEpg a metodu PVRIpTvData::LoadEPG podle větve master.
