### ISSUE TITLE
Zvuk jede obraz po cca 10s

### ISSUE THREAD

**Issue by djlucas123456** [PepaRokos/pvr.sledovanitv#17]
Zdravím bylo by možné opravit nebo poradit mi jak to opravit ze po přepnutí na jiný program se zapne zvuk ale obraz najede až po cca 10-15 sekundách.

**Comment by johny-mnemonic** [comment]
@djlucas123456 obávám se, že se ptáš na špatném místě. Pokud používáš PVR plugin dostupný přímo v Kodi bez manuální instalace, tak používáš verzi z [tohoto repozitáře](https://github.com/palinek/pvr.sledovanitv.cz). Toto je původní repozitář, který autor příliš neudržuje a tak to palinek forknul a aktivně dál vyvíjí.
Jinak tvůj problém můžu potvrdit, děje se nám to doma už minimálně 4-6 měsíců také.

**Comment by PepaRokos** [comment]
Přesně tak. Kodi, čili i doplněk, jsem přestal používat, takže už ho dál nevyvíjím.

**Comment by johny-mnemonic** [comment]
@PepaRokos Nevadí. I tak moc díky za to, že jsi ho vytvořil!
