### ISSUE TITLE
Pod UBUNTU 19.10 v KODI 18.6 addon nie je k dispozícii

### ISSUE THREAD

**Issue by pa4k** [PepaRokos/pvr.sledovanitv#19]
ani po nainštalovaní cez terminál sa mi tento PVR addon nezobrazuje v doplnkoch na inštalácii KODI 18.6 ktorú mam na Ubuntu. Skúšal som addon remove-nuť a znova nainštalovať, inštalácia zbehne korektne ale v KODI tento addon stale nie je ani k povoleniu ostatné PVR addony mam naištalované a tie funguj napr. simple client.
![Snímka obrazovky z 2020-03-28 20-26-08](https://user-images.githubusercontent.com/49378254/77831931-857bad80-7132-11ea-9410-3712595088ff.png)

**Comment by johny-mnemonic** [comment]
Pokud se nepletu, tak tento plugin podporoval naposledy KODI 17.
Na KODI 18+ používej plugin přímo z KODI repozitáře a případné problémy reportuj v githubu do [nového forku.](https://github.com/palinek/pvr.sledovanitv.cz)
