### ISSUE TITLE
Podpora pro zpětné přehrávání

### ISSUE THREAD

**Issue by MiloshCZ** [PepaRokos/pvr.sledovanitv#5]
Zdravím,
bylo by možné dodělat podporu pro zpětné přehrávání? Nebo to jen neumím použít? :-D

**Comment by PepaRokos** [comment]
Možné by to určitě bylo. Naprogramovat jde lecos :-)

**Comment by palinek** [comment]
Ahojte,
 cez vikend som sa trochu (dost) vrtal v tomto addone a podarilo sa mi dostat do funkcneho stavu prehravanie z archivu. Zatial je to dvojkrokovo tzn. v EPG vybrat a spravit si nahravku a potom pustit z nahravok (tusim, ze v Kodi v18 uz bude lepsie API pre priame prehravanie z EPG, tak potom by som to este upravil). Popri tom som dost aj prekopal logiku toho addonu pre loading EPG atd.

Mne to na desktop-e funguje dobre, ale chcel by som to vyskusat aj na Raspberry Pi -> @PepaRokos mozes mi, prosim, dat nejake how to, ako vyrabas balik pre RPi?

Ak by bolo vsetko OK, spravim PR, aby mohli vyskusat aj ostatni.

**Comment by PepaRokos** [comment]
Ahoj,
super, zase se to posune o kousek dál. Ke cross buildu je potřeba toolchain pro RPi, který je tu: https://github.com/raspberrypi/tools a chroot, který jsem vyrobil podle návodu zde: https://www.raspberrypi.org/forums/viewtopic.php?t=76178. Pak je potřeba dát k projektu addonu (třeba do build adresáře) tento soubor: [rpi_cmake.txt](https://github.com/PepaRokos/pvr.sledovanitv/files/1826599/rpi_cmake.txt), změnit v něm cesty k toolchanu a chrootu a do parametrů cmake dopsat -DCMAKE_TOOLCHAIN_FILE=cesta/k/rpi_cmake.txt. Po doběhnutí cmake už klasicky make a v build adresáři by měla vzniknout knihovna s addonem.

**Comment by palinek** [comment]
Tak som to napokon skompiloval rovno na RPi v raspbiane a nasledne mi addon funguje v libreelec.

Ak by niekto chcel vyskusat: https://github.com/palinek/pvr.sledovanitv/tree/epg_timer_rec

Ale este to stale nie je, ako by som si predstavoval, lebo loading playlistu (resp. ine operacie z obsluzneho threadu) mozu blokovat ziskavanie informacii pre Kodi, takze to este chcem upravit.

**Comment by MiloshCZ** [comment]
Měl bych dotaz, co když nemám zakoupený balíček pro nahrávání, ale jen pro zpětné přehrávání pro Novu a spol.

**Comment by palinek** [comment]
> Měl bych dotaz, co když nemám zakoupený balíček pro nahrávání

Je take nieco mozne? Kazdopadne cele toto je len barla, ako sa k tej historii dostat.

Co sa tyka Kodi, tak som do toho robil prvy raz. Myslim si, ze by nejakym sposobom z addon-u mala byt moznost vynutit pustenie nejakeho stream-u (kedze tu URL streamu pre prehratie z historie vieme), ale neviem ako. Ak je niekto, kto ma taketo skusenosti s Kodi, toto by bolo idealne riesenie.

**Comment by MiloshCZ** [comment]
Možné to je, je to balíček NP +
Jasné, chápu že se jedná o berličku. Já bych asi nebyl schopný ani toho (nejsem programátor, zvládnu program opravit, případně trošku upravit, ale...)

**Comment by palinek** [comment]
> Možné to je, je to balíček NP +

Taky [tam](https://sledovanitv.cz/service) nevidim :) Zrejme to mas nie priamo od nich, ale od nejakeho ich partnera, nie?

Teraz ma este napada, ze by sa to dalo spravit dalsou barlou, tzn. ja (ako sledovanitv addon) by som Kodi tvrdil, ze tu nahravku mas, ale v skutocnosti by sa na backend nic nekomunikovalo.... a pri spusteni by potom isiel stream z "timeshift" URL... a nie z "record" URL. Este sa na to pozriem... akurat neviem, ako mi to vyjde s casom.

**Comment by MiloshCZ** [comment]
Já na nic nespěchám. Aktuálně sledovanitv používám z prohlížeče. Kdyby se povedlo to rozběhnout z kodi, tak by to bylo super.
je možné že ten můj balíček je od partnera:
![image](https://user-images.githubusercontent.com/13035760/37651215-b0a2bcfc-2c37-11e8-8961-14c87e7f702c.png)

**Comment by palinek** [comment]
@MiloshCZ v #7 je uz aj ta barla 2 pre vytvorenie "virtualnej" nahravky, aby sa dalo prehravat aj bez "ulozenia na backend server".

Prehravanie/nahravanie je teraz mozne cez EPG a "Add timer"... je mozne vybrat z typov:
- "Timer rule(guide-based)" -> vytvori nahravku na backend serveri
- "Virtual for timeshift" -> vytvori/nahradi virtualnu "timeshift" nahravku

...dalej je upravena logika tak, aby addon co najmenej (tzn. vobec) blokoval Kodi frontend

**Comment by MiloshCZ** [comment]
Skvělé, bylo by možné vystavit zkompilovaný plugin pro PC? Vyzkoušel bych to.

**Comment by palinek** [comment]
> vystavit zkompilovaný plugin pro PC?

Aky OS?

**Comment by MiloshCZ** [comment]
Jsem nenapsal :-D Windows

**Comment by palinek** [comment]
Tak s tym ja nepomozem... vedel by som poskytnut pre Debian/testing x86_64 alebo Raspbian/stable arm

**Comment by MiloshCZ** [comment]
no, tak já si vzpomenu, jak jsem to kdysi dělal a zkusím to sám :-)

**Comment by MiloshCZ** [comment]
Tak možná se mi to povedlo zkompilovat. Uff, to je ale "práce".
Jen nevím, jestli to dělá to co má. Nějak nevidím rozdíl :-/
[pvr.sledovanitv.zip](https://github.com/PepaRokos/pvr.sledovanitv/files/1836722/pvr.sledovanitv.zip)

**Comment by palinek** [comment]
> Jen nevím, jestli to dělá to co má. Nějak nevidím rozdíl :-/

Vies si teraz cez EPG spravit nahravku na nejaku relaciu, ktora uz bezala v minulosti? Predtym to nebolo mozne... s tym novym by to malo fungovat.

UPDATE:
A dalsia vec je EPG samotne. S novou verziou addonu by mala nahrat/zobrazit historia 3 dni dozadu (po starte sa nahra len aktualny cas (co najrychlejsie) a postupne sa dohraju aj dni spatne).

**Comment by MiloshCZ** [comment]
EPG do minulosti vidím
![image](https://user-images.githubusercontent.com/13035760/37762581-fbd99cc8-2dbc-11e8-830c-9642d085f00d.png)
Ale starší věci si prohlédnout nemůžu.
![image](https://user-images.githubusercontent.com/13035760/37762618-1ef78d50-2dbd-11e8-90da-3646c06a4e17.png)
Nicméně na webu můžu:
![image](https://user-images.githubusercontent.com/13035760/37762704-66f76058-2dbd-11e8-9763-16407265baf3.png)

**Comment by palinek** [comment]
> Ale starší věci si prohlédnout nemůžu.

Ako som hovoril... je to cez timer-y a nahravky:
![screenshot](https://user-images.githubusercontent.com/10990929/37763026-46f24b6e-2dbe-11e8-8c70-7e4346067782.png)
![screenshot](https://user-images.githubusercontent.com/10990929/37763094-6aaae0f2-2dbe-11e8-979a-1bcc4717272e.png)
![screenshot](https://user-images.githubusercontent.com/10990929/37763121-7df47d3a-2dbe-11e8-85d2-e72de20a849f.png)
![screenshot](https://user-images.githubusercontent.com/10990929/37763154-97ad7e5c-2dbe-11e8-8ba5-6e84b6dc173e.png)

**Comment by MiloshCZ** [comment]
No joooo, takhle to jde.
Jde to pak nějak smazat? (jinak než ukončením Kodi)
![image](https://user-images.githubusercontent.com/13035760/37763703-18d3159a-2dc0-11e8-8caa-d4506121b351.png)

A pak, to se asi netýká tohohle pluginu, jak se dostanu dál do minulosti, než 1 den? (v nastavení mám 7 dnů). Kodi moc nepoužívám, takže to je asi spíš uživatelský problém.

**Comment by palinek** [comment]
> Jde to pak nějak smazat? (jinak než ukončením Kodi)

Zatial som to nespravil... ale ani nie je dovod to mazat.... to nie je na serveri... je to len informacia v addon-e, aby si sa ku tomu dostal. Ale ak ti to vylozene vadi, ze ti to tam svieti, mozem spravit aj ten delete.

> A pak, to se asi netýká tohohle pluginu, jak se dostanu dál do minulosti, než 1 den? (v nastavení mám 7 dnů). Kodi moc nepoužívám, takže to je asi spíš uživatelský problém.

Ja kodi tiez moc nepouzivam :)... zacal som par dni dozadu. Teraz je tam na tvrdo, ze len tie 3 dni to ide (nie je to okamzite po starte... lebo ziskanie informacii a ich spracovanie nejaky cas trva... tak aby boli nejake vysledky cim skor, loaduje sa najprv len aktualny cas a potom postupne po dnoch).

**Comment by palinek** [comment]
Ozaj... ta "Timeshift" nahravka je vzdy prave jedna, tzn. vyrobenim novej sa ta aktualna nahradi novou.

**Comment by palinek** [comment]
> (v nastavení mám 7 dnů)

V akom nastaveni? Kde sa taketo nieco nastavuje?

**Comment by MiloshCZ** [comment]
Nastavuje se to tady:
![image](https://user-images.githubusercontent.com/13035760/37765897-bb4332b0-2dc5-11e8-968f-21670558cdc4.png)

Ale i když počkám nějakou dobu, tak vidím jen historii -24h.
![image](https://user-images.githubusercontent.com/13035760/37766040-14417296-2dc6-11e8-9b5b-df4f1fb429d7.png)

Ale je možné, že je to problém kodi (mám verzi 17.6 Git:20171114-a9a7a20 - dneska stažená instalačka)

**Comment by palinek** [comment]
Heh... tak teraz vidim, ze ani mne to v GUI nezobrazuje... ale v logu (kodi.log) vidim, ze sa tie data nacitali a teda dodali Kodi:
```
11:55:10.843 T:140121202476800   DEBUG: AddOnLog: PVR Sledovanitv.cz: Loading TV show: ct1 - Otázky Václava Moravce, start=2018-03-18 12:00
11:55:10.843 T:140121202476800   DEBUG: AddOnLog: PVR Sledovanitv.cz: Loading TV show: ct1 - Zprávy, start=2018-03-18 13:00
11:55:10.843 T:140121202476800   DEBUG: AddOnLog: PVR Sledovanitv.cz: Loading TV show: ct1 - O spící princezně, šípkových růžích a uražené víle, start=2018-03-18 13:05
11:55:10.843 T:140121202476800   DEBUG: AddOnLog: PVR Sledovanitv.cz: Loading TV show: ct1 - Luděk Munzar – 85 let: Jak vyženit z pekla štěstí, start=2018-03-18 14:00
11:55:10.843 T:140121202476800   DEBUG: AddOnLog: PVR Sledovanitv.cz: Loading TV show: ct1 - Rozhodni obraze krásný, start=2018-03-18 14:50
```

**Comment by palinek** [comment]
> > Jde to pak nějak smazat? (jinak než ukončením Kodi)

> Zatial som to nespravil... ale ani nie je dovod to mazat.... to nie je na serveri... je to len informacia v addon-e, aby si sa ku tomu dostal. Ale ak ti to vylozene vadi, ze ti to tam svieti, mozem spravit aj ten delete.

S tymto uz sa to da aj mazat: https://github.com/palinek/pvr.sledovanitv/commit/442ceaa6cce72c61f55aa97e3d65d3dc503f4fda

**Comment by palinek** [comment]
> Ale i když počkám nějakou dobu, tak vidím jen historii -24h.

Tak asi s tym nic neurobime, lebo Kodi chce (a pouzije) len data now - 24h ~ now + nakonfigurovae_dni_epg. Takto to chce, ked som nastavil 10 dni:
```
10:08:01.723 T:139895265707776   DEBUG: AddOnLog: PVR Sledovanitv.cz: Read EPG for channel Nova International, from=2018-03-22 10:08 to=2018-04-02 11:08
```

Takze jedine reportovat bug/feature request do kodi, aby sa to tam zmenilo.

**Comment by PepaRokos** [comment]
Tak jsem tam nakonec zpětné přehrávání vyšil přes PVR API v18. Je to celkem pěkné, jde to pustit přímo z EPG. Vyžaduje to ale Kodi 18, v Kodi 17 bude chodit toto: https://github.com/palinek/pvr.sledovanitv.
