### ISSUE TITLE
kodi 18

### ISSUE THREAD

**Issue by Bekman553** [PepaRokos/pvr.sledovanitv#8]
Ahoj,

pokusil jsem se zkompilovat plugin pro Kodi 18 na RaspberryPI2 v systému OSMC. Po kompilaci úspěšně vidím plugin, ale když se ho pokusím aktivovat, vidím tuto hlášku:

```
22:11:56.097 T:1800372960 WARNING: Previous line repeats 12 times.
$/.kodi/addons/pvr.sledovanitv/pvr.sledovanitv.so.3.0.0: undefined symbol: GetEPGTagEdl
```

Netuší někdo co by to mohlo znamenat?

**Comment by PepaRokos** [comment]
Chyběla tam jedna metoda z poslední verze PVR API. Už by to mělo jet.
